// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return windows; // Linux usa as mesmas credenciais que Windows
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1w8_bAzicmn7GZ7otTyJ492_tviGgtfA',
    appId: '1:639767112265:web:4370133fbcfabfd8ad2d98',
    messagingSenderId: '639767112265',
    projectId: 'thoth-a5c7a',
    authDomain: 'thoth-a5c7a.firebaseapp.com',
    databaseURL: 'https://thoth-a5c7a-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'thoth-a5c7a.firebasestorage.app',
    measurementId: 'G-TBL4D1S4ZS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAM3mUjcUnJmfxusAhi2zO7amWAdNGIl4w',
    appId: '1:639767112265:android:9235ac953e54c7acad2d98',
    messagingSenderId: '639767112265',
    projectId: 'thoth-a5c7a',
    databaseURL: 'https://thoth-a5c7a-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'thoth-a5c7a.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1w8_bAzicmn7GZ7otTyJ492_tviGgtfA',
    appId: '1:639767112265:windows:9235ac953e54c7acad2d98',
    messagingSenderId: '639767112265',
    projectId: 'thoth-a5c7a',
    authDomain: 'thoth-a5c7a.firebaseapp.com',
    databaseURL: 'https://thoth-a5c7a-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'thoth-a5c7a.firebasestorage.app',
    measurementId: 'G-TBL4D1S4ZS',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1w8_bAzicmn7GZ7otTyJ492_tviGgtfA',
    appId: '1:639767112265:macos:9235ac953e54c7acad2d98',
    messagingSenderId: '639767112265',
    projectId: 'thoth-a5c7a',
    authDomain: 'thoth-a5c7a.firebaseapp.com',
    databaseURL: 'https://thoth-a5c7a-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'thoth-a5c7a.firebasestorage.app',
    measurementId: 'G-TBL4D1S4ZS',
  );
}
