name: Build Flutter APK

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.3'
          channel: stable
          cache: true

      - name: Setup Keystore
        run: |
          mkdir -p ~/.android
          if [ -n "${{ secrets.KEYSTORE_BASE64 }}" ]; then
            echo "A usar keystore dos secrets..."
            echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > ~/.android/debug.keystore
          else
            echo "A criar keystore novo (primeira vez)..."
            keytool -genkeypair -v \
              -keystore ~/.android/debug.keystore \
              -alias androiddebugkey \
              -keyalg RSA -keysize 2048 \
              -validity 10000 \
              -storepass android \
              -keypass android \
              -dname "CN=Android Debug,O=Android,C=US"
            echo ""
            echo "========== COPIA ESTE BASE64 PARA O SECRET KEYSTORE_BASE64 =========="
            base64 -w 0 ~/.android/debug.keystore
            echo ""
            echo "====================================================================="
            echo ""
            echo "========== SHA-1 =========="
            keytool -list -v \
              -keystore ~/.android/debug.keystore \
              -alias androiddebugkey \
              -storepass android \
              -keypass android \
              | grep "SHA1:"
            echo "==========================="
          fi

      - name: Flutter Version
        run: flutter --version

      - name: Clean Project
        run: flutter clean

      - name: Install Dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
